---
title: "Bayesian HSMM Approximation"
author: "Beniamino Hadj-Amar"
date: "20/03/2020"
output: html_document
---


## Set up

```{r set_up, include=TRUE, echo=FALSE, eval=TRUE, cache=TRUE, results='hide'}

setwd("/Users/beniamino/Desktop/HSMM_Project/")

source("util.R")
source("util_bayes.R")
library("rstan")
library("bayesplot")
library("bridgesampling")
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```

# --------------- Data Generation 

```{r data_generation, include=TRUE,echo=TRUE, eval=TRUE,cache=TRUE,results='hide'}

# -- Parameterization

N <- 200  # length time series
parms <- list()
parms$K <- 3  # n. states
parms$lambda <- c(20, 30, 20) # poisson duration rate
parms$mu <- c(5, 14, 30)  # emission parameter - mean
parms$sigma <- c(1, 1, 1) # emission parameters - sd
parms$gamma <- matrix(c(0, 0.3, 0.7,
                        0.2, 0, 0.8,
                        0.1, 0.9, 0), parms$K, parms$K, byrow = T) #  t.p.m
parms$delta <- c(1.0, 0.0, 0.0) # initial dstr

# - Simulate data

set.seed(5)
simul <- gauss.HSMM.generate_sample(N, parms)
obs <- simul$obs
state <- simul$state
plot(obs, col = state, cex = 0.7, pch = 20, type = "o")
```




# ------------ Expectation/Conditional Maximization (ECM)


```{r ECM, include=TRUE, echo=TRUE, eval=TRUE,cache=TRUE,results='hide'}

K <- 3
m <- rep(5, K)
parms.0 <- pars.init(obs, K) # initial values
ECM <- HSMM.ECM(K = K, m = m, obs = obs, parms_init = parms.0, niter = 3e2)
```

```{r ECM_out, include=TRUE, echo=TRUE, eval=TRUE, cache=TRUE, results='hide'}
cat("mllk:", ECM$mllk, " AIC:", ECM$AIC, " BIC:", ECM$BIC, "\n")
HSMM.pseudo_residuals(obs, m, ECM$lambda, 
                      ECM$mu, ECM$sigma, ECM$gamma, plt = TRUE)
HSMM.viterbi(obs, m, ECM$lambda, ECM$mu, ECM$sigma, ECM$gamma, plt = TRUE)
```




# ------------ Maximum Likelihood Estimator (MLE) 


```{r MLE, include=TRUE, echo=TRUE, eval=TRUE,cache=TRUE,results='hide'}
K <- 3
m <- rep(5, K)
parms.0 <- pars.init(obs, K) # initial values
MLE <- HSMM.mle(K, obs, parms.0)
```

```{r MLE_out, include=TRUE, echo=TRUE, eval=TRUE,cache=TRUE,results='hide'}
cat("mllk:", MLE$mllk, " AIC:", MLE$AIC, " BIC:", MLE$BIC, "\n")
HSMM.pseudo_residuals(obs, m, MLE$lambda, 
                      MLE$mu, MLE$sigma, MLE$gamma, plt = TRUE)
HSMM.viterbi(obs, m, MLE$lambda, MLE$mu, MLE$sigma, MLE$gamma, plt = TRUE)
```






# --------------- Bayesian Model 

```{r bayes, include=TRUE, echo=TRUE, eval=TRUE,cache=TRUE,results='hide'}

model.stan <- stan_model(file="bayesHSMMapprox.stan")
data.stan <- list(N = length(obs), K = K, y = obs,
                  m = m,  mu_0 = rep(0, K),
                  sigma_0 = 10, a_0 = 8, b_0 = 1, alpha_0 = 1)
fit.stan <- sampling(object = model.stan, data = data.stan,
                     warmup = 1000, iter=(1+5)*1000, chains = 1, cores = 1,
                     control = list(adapt_delta=0.95, stepsize=0.01, max_treedepth = 20))
print(fit.stan, probs = c(0.05, 0.95))$summary
```

```{r bayes_out, include=TRUE, echo=TRUE, eval=TRUE,cache=TRUE,results='hide'}

# -- extracting samples 
sims <- extract(fit.stan)
lambda_sims <- sims$lambda
mu_sims <- sims$mu
sigma_sims <- sims$sigma
gamma_sims <- get.gamma_sims(sims$gamma)

# --- bayes estimates
lambda.hat <- colMeans(lambda_sims)
mu.hat <- colMeans(mu_sims)
sigma.hat <- colMeans(sigma_sims)
gamma.hat <- apply(gamma_sims, c(1, 2), mean)

```


```{r bayes_diag, include=TRUE, echo=TRUE, eval=TRUE,cache=TRUE,results='hide'}

# --- trace plots + hist transitions
mcmc_trace(as.array(fit.stan), regex_pars = "gamma")
mcmc_trace(as.array(fit.stan), regex_pars = "mu")
mcmc_trace(as.array(fit.stan), regex_pars = "sigma")
mcmc_trace(as.array(fit.stan), regex_pars = "lambda")
HSMM.transitions.hist(gamma_sims)
```

```{r bayes_diag, include=TRUE, echo=TRUE, eval=TRUE,cache=TRUE,results='hide'}

HSMM.pseudo_residuals(obs, m, lambda.hat, mu.hat, sigma.hat, gamma.hat, plt = TRUE)
HSMM.viterbi(obs, m, lambda.hat, mu.hat, sigma.hat,gamma.hat, draw = FALSE, plt = TRUE) 

```


```{r bayes_diag, include=TRUE, echo=TRUE, eval=TRUE,cache=TRUE,results='hide'}

# -- posterior predictive plot check
HSMM.predictive.plot(sims, obs, m)
```

```{r bayes_diag, include=TRUE, echo=TRUE, eval=TRUE,cache=TRUE,results='hide'}
# --- predictive performances
pred.perf <- HSMM.performance(sims, obs, m)
pred.perf
```





## --------------- Summary Parameter Estimates



```{r bayes_mu, include=TRUE, echo=TRUE, eval=TRUE,cache=TRUE,results='hide'}

# mu
print(fit.stan, pars = "mu")
cat("\n ECM: ", ECM$mu)
cat("\n MLE: ", MLE$mu)
cat("\n")
```
```{r bayes_sigma, include=TRUE, echo=TRUE, eval=TRUE,cache=TRUE,results='hide'}

# sigma
print(fit.stan, pars = "sigma")
cat("\n ECM: ", ECM$sigma)
cat("\n MLE: ", MLE$sigma)
cat("\n")
```

```{r bayes_lambda, include=TRUE, echo=TRUE, eval=TRUE,cache=TRUE,results='hide'}

# lambda
print(fit.stan, pars = "lambda")
cat("\n ECM: ", ECM$lambda)
cat("\n MLE: ", MLE$lambda)
cat("\n")
```

```{r bayes_gamma, include=TRUE, echo=TRUE, eval=TRUE,cache=TRUE,results='hide'}

# gamma
print(fit.stan, pars = "gamma")
cat("\n ECM: \n"); print(ECM$gamma)
cat("\n MLE: \n"); print(MLE$gamma)
cat("\n")
```

